name: nimble test
on:
  push:
    branches-ignore:
      - 'feat-*'
    paths:
      - '**/*.nim'
      - './*.nimble'
      - 'tests/**'
      - '.github/workflows/ci.yml'
  pull_request:
  workflow_dispatch:
env:
  nim-version: '2.2.8'
jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v4
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble
    - uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: ${{ env.nim-version }}

    - name: test
      run: nimble test

    - name: test js
      if: runner.os == 'Linux'
      run: nimble test -b:js -d:nodejs
